version: '3.7'

services:

  pipe-rt-manager:
    container_name: pipe-rt-manager
    build:
      context: .
      dockerfile: Dockerfile
      args:
        http_proxy:
        https_proxy:
        no_proxy:
        socks_proxy:
    ports:
      - '8080:3000'