FROM node:13-alpine3.11 AS builder
WORKDIR /app
COPY . .
EXPOSE 8080

RUN yarn install
RUN yarn run build

FROM node:13-alpine3.11
RUN yarn global add serve
WORKDIR /app
COPY --from=builder /app/build .
CMD ["serve", "-p", "8080", "-s", "."]doc