FROM node:13-alpine3.11

# Create app directory
WORKDIR /usr/src/app

# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 8080

# WORKDIR /usr/src/app/pipertmngr-client

RUN yarn install

CMD [ "npm", "start" ]